Avoid mod_shout on sid/jessie for now
On sid the build breaks on "undefined reference to symbol
'ogg_sync_init'".  We'll just avoid mod_shout on sid/jessie until this
is worked out.